### ISSUE TITLE
Quadro do banner

### ISSUE THREAD

**Issue by ammanga** [Amarelo-Manga/edgard-raoul#1]
- [x] Aumentar Fonte
- [x] Aumentar o Quadrado para ficar parecido com o layout
- [x] Deixar o texto em quatro linhas
- [x] Alinhar o quadrdo conforme o Layout

**Comment by walacefex** [comment]
Essas alterações feitas
![screen shot 2018-02-22 at 15 23 01](https://user-images.githubusercontent.com/16948390/36556585-9e2dcd08-17fd-11e8-8e33-fb89ae23d303.png)
