### ISSUE TITLE
Excluir Descrição no campo Fotos

### ISSUE THREAD

**Issue by ammanga** [Amarelo-Manga/edgard-raoul#3]
Confira fotos de nosso aventureiro em suas viagens. 

Texto Correto:

Confira fotos de  suas viagens.

**Comment by walacefex** [comment]
Frase trocada nos dois idiomas
![screen shot 2018-02-22 at 15 49 48](https://user-images.githubusercontent.com/16948390/36557900-6d032684-1801-11e8-9849-58eed7bc774a.png)
![screen shot 2018-02-22 at 15 50 00](https://user-images.githubusercontent.com/16948390/36557902-6e0be1f6-1801-11e8-8386-643713125efa.png)
